"""Global pytest bootstrap for CI-safe collection."""

from __future__ import annotations

import json
import os
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent

os.environ.setdefault("FACTORY_API_KEY_1", "test")
os.environ.setdefault("FACTORY_API_NAME_1", "test_model")

env_path = _REPO_ROOT / ".env"
if not env_path.exists():
    env_path.write_text(
        "# Auto-generated by conftest.py for CI test collection\n"
        "FACTORY_API_KEY_1=test\n"
        "FACTORY_API_NAME_1=test_model\n",
        encoding="utf-8",
    )

qwen_dir = _REPO_ROOT / ".qwen"
qwen_dir.mkdir(parents=True, exist_ok=True)
oauth_path = qwen_dir / "oauth_creds.json"
if not oauth_path.exists():
    oauth_path.write_text(
        json.dumps({"access_token": "test"}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
