"""Pytest bootstrap for CI collection stability.

Ensures minimal env/files required by modules that import ``factory.config`` at import time.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path


# Repository root: <repo>/factory/tests/conftest.py -> parents[2] == <repo>
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))


def _ensure_ci_env() -> None:
    """Provide fallback API account vars so import-time config does not crash."""
    os.environ.setdefault("FACTORY_API_KEY_1", "test")
    os.environ.setdefault("FACTORY_API_NAME_1", "test_model")


def _ensure_ci_files() -> None:
    """Create minimal placeholder files expected by some import-time paths."""
    env_path = _REPO_ROOT / ".env"
    if not env_path.exists():
        env_path.write_text(
            "# Auto-generated by factory/tests/conftest.py for CI test collection\n"
            "FACTORY_API_KEY_1=test\n"
            "FACTORY_API_NAME_1=test_model\n",
            encoding="utf-8",
        )

    qwen_dir = _REPO_ROOT / ".qwen"
    qwen_dir.mkdir(parents=True, exist_ok=True)
    oauth_path = qwen_dir / "oauth_creds.json"
    if not oauth_path.exists():
        oauth_path.write_text(
            json.dumps({"access_token": "test"}, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )


_ensure_ci_env()
_ensure_ci_files()
